# Generated by Django 2.2.10 on 2020-11-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('T', 'Ответ с текстом'), ('CO', 'Выбор одного варианта'), ('CM', 'Выбор нескольких вариантов')], max_length=50, verbose_name='Тип вопроса'),
        ),
    ]
