# Generated by Django 2.2.10 on 2020-11-20 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0009_auto_20201120_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date_start',
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата старта'),
            preserve_default=False,
        ),
    ]
