# Generated by Django 2.2.10 on 2020-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0010_auto_20201120_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
