# Generated by Django 2.2.10 on 2020-11-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0011_auto_20201120_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizmain.Question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
