# Generated by Django 2.2.10 on 2020-11-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0015_auto_20201122_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Ответ с текстом'), ('choose_one', 'Выбор одного варианта'), ('choose_many', 'Выбор нескольких вариантов')], max_length=50, verbose_name='Тип вопроса'),
        ),
    ]
