# Generated by Django 2.2.10 on 2020-11-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0020_auto_20201123_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
    ]
