# Generated by Django 2.2.10 on 2020-11-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0026_auto_20201126_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choices',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choice_answer', to='quizmain.Choice', verbose_name='Варианты'),
        ),
    ]
