# Generated by Django 2.2.10 on 2020-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0031_auto_20201127_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Правильный вариант'),
        ),
    ]
