# Generated by Django 2.2.10 on 2020-11-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0032_auto_20201128_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choices',
        ),
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choice_answer', to='quizmain.Choice', verbose_name='Варианты'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizmain.Question', verbose_name='Вопрос'),
        ),
    ]
