# Generated by Django 2.2.10 on 2020-11-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0036_auto_20201129_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quiz_answer', to='quizmain.Quiz', verbose_name='Опрос'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
    ]
