# Generated by Django 2.2.10 on 2020-11-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0037_auto_20201129_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('quiz', models.ManyToManyField(blank=True, related_name='respondent', to='quizmain.Quiz', verbose_name='Опрос')),
            ],
        ),
    ]
