# Generated by Django 2.2.10 on 2020-12-02 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0038_respondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondent_answer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
