# Generated by Django 2.2.10 on 2020-12-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0039_auto_20201202_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
