# Generated by Django 2.2.10 on 2020-12-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0042_auto_20201203_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respondent',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
