# Generated by Django 2.2.10 on 2020-12-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0043_auto_20201203_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respondent',
            options={'verbose_name': 'Респондент', 'verbose_name_plural': 'Респонденты'},
        ),
    ]
