# Generated by Django 2.2.10 on 2020-12-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0044_auto_20201203_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='quiz',
        ),
    ]
