# Generated by Django 2.2.10 on 2020-12-05 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizmain', '0045_remove_respondent_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='respondent',
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sessions.Session', verbose_name='Сессия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
