# Generated by Django 2.2.10 on 2020-12-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0046_auto_20201205_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_answers', to='sessions.Session', verbose_name='Сессия'),
        ),
    ]
