# Generated by Django 2.2.10 on 2020-12-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0052_auto_20201207_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_respondent', to='quizmain.Quiz', verbose_name='Опрос'),
            preserve_default=False,
        ),
    ]
