# Generated by Django 2.2.10 on 2020-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmain', '0053_respondent_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='quiz',
        ),
        migrations.AddField(
            model_name='respondent',
            name='quiz',
            field=models.ManyToManyField(related_name='quiz_respondent', to='quizmain.Quiz', verbose_name='Опрос'),
        ),
    ]
